- name: Install Java, Tomcat, and Nexus
  hosts: all
  become: yes
  vars:
    mysql_server_ip: "{{ lookup('file', 'mysql_ip.txt') | trim }}"
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

  roles:
    - java
    - tomcat
    - mysql
